#数据库配置
spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/virtual1?serverTimezone=UTC&useSSL=false
     username: root
     password: 1234
     driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: utf-8
    mode: HTML5
  mvc:
    date-format: yyyy-MM-dd



# pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# 线程池配置
thread-pool-factory:
    #IO密集型应用，线程数为2N+1
    corePoolSize: 10
    maxPoolSize: 20
    queueCapacity: 100
    keepAliveSeconds: 120

server:
  port: 8088
